### ISSUE TITLE
Use 'polling' instead of 'pooling'

### ISSUE THREAD

**Issue by rcandea** [andreimpircalaboiu/WodsUP#1]
https://en.wikipedia.org/wiki/Polling_(computer_science)

**Comment by rcandea** [comment]
We still have some 'poolings' left:

`[rcandea@thinkpad WodsUP]$ find ../WodsUP/ -regex ".*\.\(xml\|cs\)" | xargs grep OneDataSourcePooling
../WodsUP/Sources/Data/Databases/DataPollingContextHelper.cs:namespace OneDataSourcePoolingUtility.Data.Databases
../WodsUP/Sources/Data/Databases/FileDate.cs:namespace OneDataSourcePoolingUtility.Data.Databases
../WodsUP/Sources/Data/Databases/DataPollingContext.cs:namespace OneDataSourcePoolingUtility.Data.Databases
../WodsUP/Sources/Data/Databases/Connection.cs:namespace OneDataSourcePoolingUtility.Data.Databases
../WodsUP/Sources/Data/Databases/SchemaInfo.cs:namespace OneDataSourcePoolingUtility.Data.Databases
../WodsUP/Sources/Data/Databases/Poll.cs:namespace OneDataSourcePoolingUtility.Data.Databases
../WodsUP/Sources/Data/Repository/GenericRepository.cs:using OneDataSourcePoolingUtility.Data.Databases;
../WodsUP/Sources/Data/Repository/GenericRepository.cs:namespace OneDataSourcePoolingUtility.Data.Repository
../WodsUP/Sources/Data/Repository/IGenericRepository.cs:namespace OneDataSourcePoolingUtility.Data.Repository
../WodsUP/Sources/Data/Repository/DatabaseManagement.cs:using OneDataSourcePoolingUtility.Data.Databases;
../WodsUP/Sources/Data/Repository/DatabaseManagement.cs:namespace OneDataSourcePoolingUtility.Data.Repository
../WodsUP/Sources/Business/FtpService.cs:using OneDataSourcePoolingUtility.Business.BOs;
../WodsUP/Sources/Business/BOs/FileDateBo.cs:using OneDataSourcePoolingUtility.Business.Infrastructure;
../WodsUP/Sources/Business/BOs/FileDateBo.cs:namespace OneDataSourcePoolingUtility.Business.BOs
../WodsUP/Sources/Business/BOs/KeyTextBo.cs:namespace OneDataSourcePoolingUtility.Business.BOs
../WodsUP/Sources/Business/BOs/PollBo.cs:using OneDataSourcePoolingUtility.Business.Infrastructure;
../WodsUP/Sources/Business/BOs/PollBo.cs:namespace OneDataSourcePoolingUtility.Business.BOs
../WodsUP/Sources/Business/BOs/BaseBo.cs:namespace OneDataSourcePoolingUtility.Business.BOs
../WodsUP/Sources/Business/BOs/ConnectionBo.cs:namespace OneDataSourcePoolingUtility.Business.BOs
../WodsUP/Sources/Business/Constants/DayWeekType.cs:﻿namespace OneDataSourcePoolingUtility.Business.Infrastructure
../WodsUP/Sources/Business/Constants/FileDateType.cs:﻿namespace OneDataSourcePoolingUtility.Business.Infrastructure
../WodsUP/Sources/Business/Constants/MinuteType.cs:﻿namespace OneDataSourcePoolingUtility.Business.Infrastructure
../WodsUP/Sources/Business/Constants/HourType.cs:﻿namespace OneDataSourcePoolingUtility.Business.Infrastructure
../WodsUP/Sources/Business/Constants/DayMonthType.cs:﻿namespace OneDataSourcePoolingUtility.Business.Infrastructure
../WodsUP/Sources/Business/BusinessService.cs:using OneDataSourcePoolingUtility.Business.BOs;
../WodsUP/Sources/Business/BusinessService.cs:using OneDataSourcePoolingUtility.Data.Databases;
../WodsUP/Sources/Business/BusinessService.cs:using OneDataSourcePoolingUtility.Data.Repository;
../WodsUP/Sources/Business/BusinessService.cs:namespace OneDataSourcePoolingUtility.Business
../WodsUP/Sources/Business/Infrastructure/EnumUtils.cs:namespace OneDataSourcePoolingUtility.Business.Constants
../WodsUP/Sources/Business/Infrastructure/PollDetailsHelper.cs:using OneDataSourcePoolingUtility.Business.BOs;
../WodsUP/Sources/Business/Infrastructure/PollDetailsHelper.cs:namespace OneDataSourcePoolingUtility.Business.Infrastructure
../WodsUP/Sources/Business/Infrastructure/BusinessMappings.cs:using OneDataSourcePoolingUtility.Business.BOs;
../WodsUP/Sources/Business/Infrastructure/BusinessMappings.cs:using OneDataSourcePoolingUtility.Data.Databases;
../WodsUP/Sources/Business/Infrastructure/BusinessMappings.cs:namespace OneDataSourcePoolingUtility.Business.Infrastructure
../WodsUP/Sources/OneDataSourcePollingUtility/EditFileDateForm.Designer.cs:            this.FileDatesRadioGroupBox = new OneDataSourcePoolingUtility.Components.RadioGroupBox();
../WodsUP/Sources/OneDataSourcePollingUtility/EditFileDateForm.Designer.cs:        private OneDataSourcePoolingUtility.Components.RadioGroupBox FileDatesRadioGroupBox;
../WodsUP/Sources/OneDataSourcePollingUtility/PollingUtilityForm.cs:using OneDataSourcePoolingUtility.Business.BOs;
../WodsUP/Sources/OneDataSourcePollingUtility/PollingUtilityForm.cs:using OneDataSourcePoolingUtility.Business;
../WodsUP/Sources/OneDataSourcePollingUtility/PollingUtilityForm.cs:namespace OneDataSourcePoolingUtility
../WodsUP/Sources/OneDataSourcePollingUtility/PollDetailsForm.cs:using OneDataSourcePoolingUtility.Business;
../WodsUP/Sources/OneDataSourcePollingUtility/PollDetailsForm.cs:using OneDataSourcePoolingUtility.Business.BOs;
../WodsUP/Sources/OneDataSourcePollingUtility/PollDetailsForm.cs:using OneDataSourcePoolingUtility.Business.Infrastructure;
../WodsUP/Sources/OneDataSourcePollingUtility/PollDetailsForm.cs:namespace OneDataSourcePoolingUtility
../WodsUP/Sources/OneDataSourcePollingUtility/EditFileDateForm.cs:using OneDataSourcePoolingUtility.Business;
../WodsUP/Sources/OneDataSourcePollingUtility/EditFileDateForm.cs:using OneDataSourcePoolingUtility.Business.BOs;
../WodsUP/Sources/OneDataSourcePollingUtility/PollingUtilityForm.Designer.cs:﻿using OneDataSourcePoolingUtility.Business.BOs;
../WodsUP/Sources/OneDataSourcePollingUtility/PollingUtilityForm.Designer.cs:namespace OneDataSourcePoolingUtility
../WodsUP/Sources/OneDataSourcePollingUtility/PollingUtilityForm.Designer.cs:            this.pollBoBindingSource.DataSource = typeof(OneDataSourcePoolingUtility.Business.BOs.PollBo);
../WodsUP/Sources/OneDataSourcePollingUtility/AddFileDateForm.Designer.cs:﻿namespace OneDataSourcePoolingUtility
../WodsUP/Sources/OneDataSourcePollingUtility/AddFileDateForm.Designer.cs:            this.FileDatesRadioGroupBox = new OneDataSourcePoolingUtility.Components.RadioGroupBox();
../WodsUP/Sources/OneDataSourcePollingUtility/Program.cs:using OneDataSourcePoolingUtility.Infrastructure;
../WodsUP/Sources/OneDataSourcePollingUtility/Program.cs:namespace OneDataSourcePoolingUtility
../WodsUP/Sources/OneDataSourcePollingUtility/PollDetailsForm.Designer.cs:﻿using OneDataSourcePoolingUtility.Components;
../WodsUP/Sources/OneDataSourcePollingUtility/PollDetailsForm.Designer.cs:namespace OneDataSourcePoolingUtility
../WodsUP/Sources/OneDataSourcePollingUtility/PollDetailsForm.Designer.cs:            this.DayOfWeekGroupBox = new OneDataSourcePoolingUtility.Components.RadioGroupBox();
../WodsUP/Sources/OneDataSourcePollingUtility/PollDetailsForm.Designer.cs:            this.DayOfMonthGroupBox = new OneDataSourcePoolingUtility.Components.RadioGroupBox();
../WodsUP/Sources/OneDataSourcePollingUtility/PollDetailsForm.Designer.cs:            this.HoursGroupBox = new OneDataSourcePoolingUtility.Components.RadioGroupBox();
../WodsUP/Sources/OneDataSourcePollingUtility/PollDetailsForm.Designer.cs:            this.MinutesGroupBox = new OneDataSourcePoolingUtility.Components.RadioGroupBox();
../WodsUP/Sources/OneDataSourcePollingUtility/PollDetailsForm.Designer.cs:            this.FileDateBoBindingSource.DataSource = typeof(OneDataSourcePoolingUtility.Business.BOs.FileDateBo);
../WodsUP/Sources/OneDataSourcePollingUtility/Components/RadioGroupBox.cs:namespace OneDataSourcePoolingUtility.Components
../WodsUP/Sources/OneDataSourcePollingUtility/AddFileDateForm.cs:using OneDataSourcePoolingUtility.Business;
../WodsUP/Sources/OneDataSourcePollingUtility/AddFileDateForm.cs:using OneDataSourcePoolingUtility.Business.BOs;
../WodsUP/Sources/OneDataSourcePollingUtility/AddFileDateForm.cs:namespace OneDataSourcePoolingUtility
../WodsUP/Sources/OneDataSourcePollingUtility/Infrastructure/MappingConfiguration.cs:using OneDataSourcePoolingUtility.Business;
../WodsUP/Sources/OneDataSourcePollingUtility/Infrastructure/MappingConfiguration.cs:using OneDataSourcePoolingUtility.Business.Infrastructure;
../WodsUP/Sources/OneDataSourcePollingUtility/Infrastructure/MappingConfiguration.cs:namespace OneDataSourcePoolingUtility.Infrastructure
`

**Comment by RaduBogdanIoan** [comment]
Done
